### PR TITLE
302: Prevent a PHP fatal error on import

### LINKED ISSUE #302: Prevent a PHP fatal error when importing originals
Steps to reproduce:
- Create a new project
- Import https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Resources/en.lproj/Localizable.strings

> Fatal error: Call to a member function add_translations_from_other_projects() on a non-object in glotpress/gp-includes/things/original.php on line 212

### PR DESCRIPTION
**Pull request by SergeyBiryukov**
Fixes #302.

### CODE REVIEW

**Comment by SergeyBiryukov** [comment]
The first commit prevents the fatal error from #302 and makes `GP_Original::import_for_project()` return the number of errors encountered on import.

The second one trims the context field to 255 characters on import (to match the database schema). I guess it won't cause the iOS app to display the string untranslated, as the concept of context does not exist there anyway, per [#glotpress421](https://glotpress.trac.wordpress.org/ticket/421).

File: gp-includes/things/original.php [hunk 1]
```diff
@@ -107,8 +107,15 @@ public function import_for_project( $project, $translations ) {
 
 		$possibly_added = $possibly_dropped = array();
 
-		foreach( $translations->entries as $entry ) {
+		foreach( $translations->entries as $key => $entry ) {
```
Comment (toolstack) [inline gp-includes/things/original.php]: Add a space after the `foreach` keyword?

File: gp-includes/things/original.php [hunk 2]
```diff
@@ -107,8 +107,15 @@ public function import_for_project( $project, $translations ) {
...
 			$wpdb->queries = array();
+
+			// Context needs to match VARCHAR(255) in the database schema.
+			if ( gp_strlen( $entry->context ) > 255 ) {
+				$entry->context = gp_substr( $entry->context, 0, 255 );
+				$translations->entries[ $entry->key() ] = $entry;
```
Comment (toolstack) [inline gp-includes/things/original.php:143]: Instead of re-assigning the entire `$entry` should it just assign the context? ie:

`$translations->entries[ $entry->key() ]->context = $entry->context;`

Just so we don't change the array that we're already in the middle of looping through?

Comment (SergeyBiryukov) [inline gp-includes/things/original.php:143]: We do need to assign the entire `$entry` here, because trimming `$entry->context` changes `$entry->key()`, and the `array_key_exists( $key, $translations->entries )` check fails later.

Without this assignment, the affected string ends up in `$possibly_dropped` and gets repeatedly removed / re-added on each subsequent import.

File: gp-includes/things/original.php [hunk 3]
```diff
@@ -223,7 +235,7 @@ public function import_for_project( $project, $translations ) {
 		}
 
 		// Clear cache when the amount of strings are changed.
-		if ( $originals_added > 0 || $originals_existing > 0 || $originals_fuzzied > 0 || $originals_obsoleted > 0 ) {
+		if ( $originals_added > 0 || $originals_existing > 0 || $originals_fuzzied > 0 || $originals_obsoleted > 0 || $originals_error > 0 ) {
```
Comment (ocean90) [inline gp-includes/things/original.php]: Why would we have to clear the cache if an original wasn't added?

File: gp-includes/things/original.php (hunk 1 above)
Comment (SergeyBiryukov) [inline gp-includes/things/original.php]: Done.

File: gp-includes/things/original.php (hunk 3 above)
Comment (SergeyBiryukov) [inline gp-includes/things/original.php]: Good catch, fixed.

File: gp-includes/things/original.php (hunk 2 above)
Comment (toolstack) [inline gp-includes/things/original.php:143]: Aren't we then creating 'duplicate' entries?  Do we need to delete the old entry from the array?

Comment (ocean90) [inline gp-includes/things/original.php:143]: Thought about this a bit and I think can't remove the other entry or stop the processing because otherwise an existing original doesn't get updated.

Comment (ocean90) [inline gp-includes/things/original.php:143]: > We do need to assign the entire `$entry` here, because trimming `$entry->context` changes `$entry->key()`

For some reasons `$entry->key()` remains the same here.

```
.array(2) {
  ["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafooo"]=>
  object(Translation_Entry)#205 (9) {
    ["is_plural"]=>
    bool(false)
    ["context"]=>
    string(255) "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    ["singular"]=>
    string(4) "fooo"
    ["plural"]=>
    NULL
    ["translations"]=>
    array(0) {
    }
    ["translator_comments"]=>
    string(0) ""
    ["extracted_comments"]=>
    string(0) ""
    ["references"]=>
    array(0) {
    }
    ["flags"]=>
    array(0) {
    }
  }
  ["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafooo"]=>
  object(Translation_Entry)#205 (9) {
    ["is_plural"]=>
    bool(false)
    ["context"]=>
    string(255) "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    ["singular"]=>
    string(4) "fooo"
    ["plural"]=>
    NULL
    ["translations"]=>
    array(0) {
    }
    ["translator_comments"]=>
    string(0) ""
    ["extracted_comments"]=>
    string(0) ""
    ["references"]=>
    array(0) {
    }
    ["flags"]=>
    array(0) {
    }
  }
}
```

File: tests/tests_things/test_thing_original.php [hunk 4]
```diff
@@ -185,19 +185,54 @@ function test_by_project_id_and_entry_should_match_case() {
...
+
+		$this->assertCount( 3, $translations_for_import_orig->entries );
+
+		list( $originals_added, $originals_existing, $originals_fuzzied, $originals_obsoleted, $originals_error ) = GP::$original->import_for_project( $project, $translations_for_import_orig );
+
+		// Originals are already imported, no change.
+		$this->assertEquals( 0, $originals_added );
+		$this->assertEquals( 0, $originals_existing );
+		$this->assertEquals( 0, $originals_fuzzied );
+		$this->assertEquals( 0, $originals_obsoleted );
```
Comment (ocean90) [inline tests/tests_things/test_thing_original.php:228]: This line is failing, it returns 2 for `$originals_obsoleted`.
