### PR TITLE
547: Fix empty cancel link

### LINKED ISSUE #547: Cancel link on projects/-new can have an empty href attribute
``` html
<p>
        <input type="submit" name="submit" value="Create" id="submit" />
        <span class="or-cancel">or <a href="">Cancel</a></span>
</p>
```

Notice the empty href attribute. This happens if `GP_URL_BASE` is `'/'` and the current permalink structure has no trailing slash.

### PR DESCRIPTION
**Pull request by toolstack**
The cancel link can be blank if GP is install in the root of a domain and the permalink structure is set to have no trailing slash.

Resolves #547.

### CODE REVIEW

File: gp-templates/project-new.php [hunk 1]
```diff
@@ -10,7 +10,7 @@
 <?php gp_tmpl_load( 'project-form', get_defined_vars()); ?>
 	<p>
 		<input type="submit" name="submit" value="<?php esc_attr_e( 'Create', 'glotpress' ); ?>" id="submit" />
-		<span class="or-cancel"><?php _e( 'or', 'glotpress' ); ?> <a href="<?php echo gp_url(); ?>"><?php _e( 'Cancel', 'glotpress' ); ?></a></span>
+		<span class="or-cancel"><?php _e( 'or', 'glotpress' ); ?> <a href="<?php echo gp_url_public_root(); // WPCS: XSS ok. ?>"><?php _e( 'Cancel', 'glotpress' ); ?></a></span>
```
Comment (ocean90) [inline gp-templates/project-new.php]: XSS is not ok. 😄  Let's wrap it with `esc_url()`.

**Review by ocean90 — CHANGES_REQUESTED** [review]

File: gp-templates/project-new.php (hunk 1 above)
Comment (toolstack) [reply gp-templates/project-new.php]: Done.

**Review by ocean90 — APPROVED** [review]
