### PR TITLE
388: Fix project path during upgrade

### LINKED ISSUE #388: "Not found" error when attempting to view and edit sub-projects
We have GlotPress 2.0 running on a secondary site in a multisite instance, and GlotPress throws a "Not found" error when attempting to view or edit a sub-project. We've tried multiple permalink settings, with and without a trailing slash, but no luck.

GlotPress version: 2.0
WordPress version: 4.4.2
Configuration: directory-based multisite, HTTPS

### PR DESCRIPTION
**Pull request by toolstack**
Resolves #388.

### CODE REVIEW

File: gp-includes/install-upgrade.php [hunk 1]
```diff
@@ -10,9 +21,21 @@ function gp_upgrade_db() {
...
 function gp_upgrade_data( $db_version ) {
 	global $wpdb;
+
 	if ( $db_version < 190 ) {
-		$wpdb->query("UPDATE $wpdb->gp_translations SET status = REPLACE(REPLACE(status, '-', ''), '+', '');");
+		$wpdb->query( "UPDATE {$wpdb->gp_translations} SET status = REPLACE(REPLACE(status, '-', ''), '+', '');" );
+	}
+
+	if ( $db_version < 950 ) {
+		$wpdb->query( "UPDATE {$wpdb->gp_projects} SET `path`=SUBSTR(`path`, 1, LENGTH(`path`) - 1) WHERE `path` LIKE '%/';" );
```
Comment (ocean90) [inline gp-includes/install-upgrade.php]: This needs to be `CHAR_LENGTH()` and let's use `SUBSTRING()`. Some whitespace before/after the equal sign would be nice too.

File: glotpress.php [hunk 2]
```diff
@@ -27,7 +27,7 @@
  */
 
 define( 'GP_VERSION', '2.1.0-alpha' );
-define( 'GP_DB_VERSION', '940' );
+define( 'GP_DB_VERSION', '950' );
```
Comment (ocean90) [inline glotpress.php:30]: 940 was a SVN revision, should we change the version to a date?

Comment (toolstack) [inline glotpress.php:30]: I wondered where the number came from.

Either just an incrementing number (I chose ten, but any increment would do) or date.

Date is kind of ugly and does limit us to once change a day :wink:.
