### PR TITLE
656: Return locale glossary if a project has no glossary

### LINKED ISSUE #656: get_extended_glossary() doesn't return locale glossary if a project has no glossary
[`GP::$glossary->by_set_or_parent_project()` returns false](https://github.com/GlotPress/GlotPress-WP/blob/2.3.0/gp-includes/routes/translation.php#L667) if a project has no glossary, which means the [`$glossary instanceof GP_Glossary` condition](https://github.com/GlotPress/GlotPress-WP/blob/2.3.0/gp-includes/routes/translation.php#L678) fails and thus no glossary gets returned.

### PR DESCRIPTION
**Pull request by ocean90**
Fixes #656.

### CODE REVIEW

File: tests/phpunit/testcases/tests_things/test_thing_glossary.php [hunk 1]
```diff
@@ -144,6 +144,32 @@ function test_locale_glossary() {
...
+			'term' => 'Term 2',
+			'part_of_speech' => 'noun',
+			'translation' => 'Translation 2',
+			'glossary_id' => $locale_glossary->id,
+		) );
+
+		$route = new Testable_GP_Route_Translation;
+		$extended_glossary = $route->testable_get_extended_glossary( $set, $set->project );
+		$this->assertInstanceOf( 'GP_Glossary', $extended_glossary );
+		$this->assertCount( 1, $extended_glossary->get_entries() );
```
Comment (akirk) [inline tests/phpunit/testcases/tests_things/test_thing_glossary.php]: I think it would be good to also test that this one entry is indeed `Term 2`, something like in line 145.

**Review by akirk — CHANGES_REQUESTED** [review]
Other than the small addition to the unit test it looks good to me!

**Review by akirk — APPROVED** [review]

**Review by toolstack — APPROVED** [review]
:+1:

**Comment by toolstack** [comment]
Do we want to do a 2.3.1 release of just leave this for 2.4?

**Comment by ocean90** [comment]
@toolstack Since locale glossaries are currently fundamentally broken I'd like to do a quick release.

**Comment by toolstack** [comment]
@ocean90 sounds good.
