### PR TITLE
Fix hooks in translation set filters/sort

### LINKED ISSUE #391: Hook `gp_translation_set_filters` needs do be moved or renamed
Hook is run after the translation set sort form, rather than the filters form.
Its current position doesn't allow additions to the filters form.

### PR DESCRIPTION
**Pull request by yoavf**
- Deprecate `gp_translation_set_filters` in favor of `gp_translation_set_sort_form`
- Introduce `gp_translation_set_filters_form` 

Fixes #391

### CODE REVIEW

File: gp-templates/translations.php [hunk 1]
```diff
@@ -165,9 +174,20 @@
 		 *
 		 * This action is inside a DL element.
 		 *
+		 * @deprecated 2.1.0 Call gp_translation_set_sort_form instead
```
Comment (ocean90) [inline gp-templates/translations.php:177]: Instead of having both filters in the template, what do you think about calling it via `gp_translation_set_sort_form`?

```
add_action( 'gp_translation_set_sort_form', function() {
    do_action( 'gp_translation_set_filters' );
}, 5 );
```

Comment (toolstack) [inline gp-templates/translations.php:177]: I prefer keeping it in the template so it's obvious to developers that the old call is deprecated and will eventually be removed.

Placing it in a call from another `do_action()` seems too much like hiding it to me :wink:.

Comment (yoavf) [inline gp-templates/translations.php:177]: @ocean90 that's a nice and clean workaround, but I agree with @toolstack that it's better being explicit here.

Comment (ocean90) [inline gp-templates/translations.php:177]: Sounds good.

File: gp-templates/translations.php [hunk 2]
```diff
@@ -165,9 +174,20 @@
...
 		 * @since 1.0.0
 		 */
-		do_action( 'gp_translation_set_filters' ); ?>
+		do_action( 'gp_translation_set_filters' );
+
+		/**
+		* Fires after the translation set sort options.
```
Comment (ocean90) [inline gp-templates/translations.php]: The block needs one more space before the `*`.
