### PR TITLE
381: "Use as Name" fix

### LINKED ISSUE #381: "Use as name" on translation set creation page does not work
Create a new translation set, select a locale and then click "Use as name" and the name field is not populated.

The javascript that does the work is wrapped in an anonymous jQuery function that does not seem to be working any more.

### PR DESCRIPTION
**Pull request by toolstack**
Fixes #381.

### CODE REVIEW

File: gp-templates/translation-set-form.php [hunk 1]
```diff
@@ -15,7 +15,7 @@
 	<dt><label for="set[project_id]"><?php _e( 'Project', 'glotpress' ); ?></label></dt>
 	<dd><?php echo gp_projects_dropdown( 'set[project_id]', $set->project_id, null, null, true ); ?></dd>
 </dl>
-<?php echo gp_js_focus_on( 'set[locale]' ) . "\n"; ?>
+<?php echo gp_js_focus_on( 'set[locale]' ) . "\n"; // WPCS: sanitization ok. ?>
```
Comment (ocean90) [inline gp-templates/translation-set-form.php]: That's the wrong comment.

 `gp_js_focus_on()` should to be added to https://github.com/GlotPress/GlotPress-WP/blob/develop/phpcs.ruleset.xml#L16. But first `$html_id` in https://github.com/GlotPress/GlotPress-WP/blob/develop/gp-includes/template.php#L235 needs to be escaped with `esc_js()`.

Comment (toolstack) [inline gp-templates/translation-set-form.php]: Is the comment still required or can it be removed?

Comment (ocean90) [inline gp-templates/translation-set-form.php]: Can be removed because it was wrong anyway.
